name: Pytest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v2
    - name: "Set up Python 3.8"
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: "Poetry Install"
      uses: dschep/install-poetry-action@v1.3
      with:
        create_virtualenvs: false
    - name: "Running tests with pytest"
      uses: cclauss/GitHub-Action-for-pytest@0.5.0
#      run: python -m pytest tests/integration --doctest-modules --disable-pytest-warnings
      env:
        PG_REMOTE_USERNAME: ${{ secrets.PG_REMOTE_USERNAME }}
        PG_REMOTE_PASSWORD: ${{ secrets.PG_REMOTE_PASSWORD }}
        PG_REMOTE_HOST: ${{ secrets.PG_REMOTE_HOST }}
        PG_REMOTE_PORT: ${{ secrets.PG_REMOTE_PORT }}
        PG_REMOTE_DATABASE: ${{ secrets.PG_REMOTE_DATABASE }}
        PG_REMOTE_SSLMODE: ${{ secrets.PG_REMOTE_SSLMODE }}
