on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pytest
    - name: Running tests with pytest
      run: |
        poetry install && python -m pytest tests/unit--doctest-modules --disable-pytest-warnings
